### 获取菜单树
GET {{host}}/sys/menu/tree
Content-Type: application/json
Authorization: {{token}}


### 添加菜单
POST {{host}}/sys/menu/add
Content-Type: application/json
Authorization: {{token}}

{
  "title": "用户管理",
  "type": 1,
  "permission": "sys:user",
  "path": "/system/user",
  "component": "system/user/index",
  "componentName": "SystemUser",
  "sort": 1,
  "parentId": 1
}


### 修改菜单
PUT {{host}}/sys/menu/edit
Content-Type: application/json
Authorization: {{token}}

{
  "id": 1,
  "title": "系统管理",
  "type": 1,
  "permission": "sys",
  "path": "/system",
  "component": "",
  "componentName": "",
  "sort": 1,
  "parentId": 0
}


### 删除菜单
DELETE {{host}}/sys/menu/delete?id=1
Content-Type: application/json
Authorization: {{token}}

