### 分页查询角色列表
POST {{host}}/sys/role/page
Authorization: {{token}}
Content-Type: application/json

### 创建角色
POST {{host}}/sys/role/add
Authorization: {{token}}
Content-Type: application/json

{
  "name": "超级管理员",
  "code": "super_admin",
  "desc": "超级管理员"
}

### 修改角色
PUT {{host}}/sys/role/edit
Authorization: {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "管理员",
  "code": "super_admin11",
  "desc": "系统管理员"
}

### 删除角色
DELETE {{host}}/sys/role/delete?id=1
Authorization: {{token}}

### 分配角色菜单
PUT {{host}}/sys/role/assign-menus
Authorization: {{token}}

{
  "roleId": 1,
  "menuIds": [1, 2]
}
}