### 分页查询角色列表
POST {{host}}/sys/role/page
Authorization: {{token}}
Content-Type: application/json

{
  "name": "管理员"
}

### 创建角色
POST {{host}}/sys/role/add
Authorization: {{token}}
Content-Type: application/json

{
  "name": "管理员1",
  "code": "admin1",
  "desc": "管理员1"
}

### 修改角色
PUT {{host}}/sys/role/edit
Authorization: {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "管理员",
  "code": "super_admin11",
  "desc": "系统管理员"
}

### 删除角色
DELETE {{host}}/sys/role/delete?id=1
Authorization: {{token}}

### 分配角色菜单
PUT {{host}}/sys/role/assign-menus
Authorization: {{token}}
Content-Type: application/json

{
  "roleId": 2,
  "menuIds": [4,5,6,7,8]
}

### 获取角色拥有的菜单
GET {{host}}/sys/role/all-simple-roles
Content-Type: application/json
Authorization: {{token}}
