### 获取菜单树
GET {{host}}/sys/menu/tree
Content-Type: application/json
Authorization: {{token}}


### 添加菜单
POST {{host}}/sys/menu/add
Content-Type: application/json
Authorization: {{token}}

{
  "name": "首页",
  "path": "/home",
  "type": 1,
  "status": 1,
  "parentId": 0,
  "component": "layout.base$view.home",
  "meta": {
    "i18nKey": "route.home",
    "icon": "mdi:monitor-dashboard",
    "order": 1
  }
}

### 修改菜单
PUT {{host}}/sys/menu/edit
Content-Type: application/json
Authorization: {{token}}

{
  "id": 3,
  "name": "首页",
  "path": "/home",
  "type": 1,
  "status": 1,
  "parentId": 0,
  "component": "layout.base$view.home",
  "meta": {
    "i18nKey": "route.home",
    "icon": "mdi:monitor-dashboard",
    "order": 2
  }
}


### 删除菜单
DELETE {{host}}/sys/menu/delete?id=3
Content-Type: application/json
Authorization: {{token}}

### 获取所有菜单简要信息
GET {{host}}/sys/menu/all/simple
Content-Type: application/json
Authorization: {{token}}

### 获取角色拥有的菜单
GET {{host}}/sys/menu/list-by-role?roleId=2
Content-Type: application/json
Authorization: {{token}}