### 用户登录
POST {{host}}/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

### 编辑用户
PUT {{host}}/sys/user/edit
Content-Type: application/json
Authorization: {{token}}

{
    "id": 1,
    "nickname": "admin",
    "email": "admin@localhost",
    "phone": "13800138000"
}
