### 用户登录
POST {{host}}/login
Content-Type: application/json

{
    "username": "gdmin",
    "password": "123456"
}

### 获取用户信息
GET {{host}}/sys/user/self/info
Content-Type: application/json
Authorization: {{token}}


### 编辑用户
PUT {{host}}/sys/user/edit
Content-Type: application/json
Authorization: {{token}}

{
    "id": 1,
    "nickname": "admin",
    "email": "admin@localhost",
    "phone": "13800138000"
}

### 分配用户角色
PUT {{host}}/sys/user/assign-roles
Content-Type: application/json
Authorization: {{token}}

{
  "id": 1,
  "roleIds": [2]
}